### ISSUE TITLE
Skylake Core i5 badly recognized

### ISSUE THREAD

**Issue by X0rg** [anrieff/libcpuid#76] opened 2016-10-23 19:51 UTC
Hi Anrieff,

The Core i5 6400 is detected as Core i7, see X0rg/CPU-X#43.

**Comment by anrieff** [comment] 2016-10-24 15:11
Thanks for the report.
I'm not 100% sure what the issue is, but I believe it's that libcpuid doesn't see the "RTM" CPU feature enabled on Linux. Probably there's no kernel support for it, so it's disabled. I have a patch in the making, that uses RDSEED instead of RTM to ascertain being on Broadwell or Skylake (in [recog_intel.c:651](https://github.com/anrieff/libcpuid/blob/master/libcpuid/recog_intel.c#L651)). I'll publish it tonight.

Btw, @X0rg - please include a facility in CPU-X to save CPUID raw dumps using `cpuid_serialize_raw_data()`. cpuid_tool works this way if you run it without options - it just writes two text files, raw.txt with the raw CPUID dump, and report.txt with the decoded info. Only raw.txt is needed for debugging. You can make `cpu-x --dump` do that in addition to the text it is printing right now.

These CPUID dumps would be of immense help with debugging issues like this one.

**Comment by 4815162342lost** [comment] 2016-10-24 16:55
I do not understand what i must to do, but there is my cpu-x --dump report:

```
vodka@vodka-PC:~$ sudo cpu-x --dump
[sudo] password for vodka: 
  >>>>>>>>>> CPU <<<<<<<<<<

	***** Processor *****
          Vendor: Intel
       Code Name: Skylake (Core i7)
         Package: U3E1
      Technology: 14 nm
         Voltage: 1,110 V
   Specification: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
          Family: 6
     Ext. Family: 6
           Model: 14 (E)
      Ext. Model: 94 (5E)
           Temp.: 33°C
        Stepping: 3
    Instructions: MMX, SSE (1, 2, 3S, 4.1, 4.2), AES, AVX, VT-x, Intel64

	***** Clocks *****
      Core Speed: 3268 MHz
      Multiplier: x32,5 (8-33)
       Bus Speed: 100,44 MHz
           Usage:  16,98 %

	***** Cache *****
         L1 Data: 4 x   32 KB,  8-way
        L1 Inst.: 4 x   32 KB,  8-way
         Level 2: 4 x  256 KB,  4-way
         Level 3:    6 MB, 12-way

	***** * *****
       Socket(s): 1
         Core(s): 4
       Thread(s): 4


  >>>>>>>>>> Caches <<<<<<<<<<

	***** L1 Cache *****
            Size: 4 x 32 KB, 8-way associative, 64-byte line size
           Speed: 68071,90 MB/s

	***** L2 Cache *****
            Size: 4 x 256 KB, 4-way associative, 64-byte line size
           Speed: 47303,30 MB/s

	***** L3 Cache *****
            Size: 6 MB, 12-way associative, 64-byte line size
           Speed: 38988,70 MB/s 
```

Please, provide for me other commands, if it is needed.

**Comment by anrieff** [comment] 2016-10-24 17:10
@4815162342lost, thanks for the dump. Unfortunately it's not giving me any more info than the screenshot. But if you run `cpuid_tool` (sudo not required), it will generate two text files in the directory you've ran it. If you could attach the generated raw.txt here that would help a lot.

**Comment by 4815162342lost** [comment] 2016-10-24 17:22
report.txt:

```
CPUID is present
CPU Info:
------------------
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz'
  family     : 6 (06h)
  model      : 14 (0Eh)
  stepping   : 3 (03h)
  ext_family : 6 (06h)
  ext_model  : 94 (5Eh)
  num_cores  : 4
  num_logical: 4
  tot_logical: 4
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 256 KB
  L3 cache   : 6144 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L2 assoc.  : 4-way
  L3 assoc.  : 12-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  SSE units  : 128 bits (non-authoritative)
  code name  : `Skylake (Core i7)'
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni pclmul dts64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 syscall xd movbe popcnt aes xsave osxsave avx rdtscp lm lahf_lm constant_tsc fma3 f16c rdrand x2apic avx2 bmi1 bmi2 sgx
```

raw.txt:
```
version=0.4.0
basic_cpuid[0]=00000016 756e6547 6c65746e 49656e69
basic_cpuid[1]=000506e3 04100800 7ffafbbf bfebfbff
basic_cpuid[2]=76036301 00f0b6ff 00000000 00c30000
basic_cpuid[3]=00000000 00000000 00000000 00000000
basic_cpuid[4]=1c004121 01c0003f 0000003f 00000000
basic_cpuid[5]=00000040 00000040 00000003 00142120
basic_cpuid[6]=000007f7 00000002 00000001 00000000
basic_cpuid[7]=00000000 029c67af 00000000 00000000
basic_cpuid[8]=00000000 00000000 00000000 00000000
basic_cpuid[9]=00000000 00000000 00000000 00000000
basic_cpuid[10]=07300804 00000000 00000000 00000603
basic_cpuid[11]=00000001 00000001 00000100 00000004
basic_cpuid[12]=00000000 00000000 00000000 00000000
basic_cpuid[13]=0000001f 00000440 00000440 00000000
basic_cpuid[14]=00000000 00000000 00000000 00000000
basic_cpuid[15]=00000000 00000000 00000000 00000000
basic_cpuid[16]=00000000 00000000 00000000 00000000
basic_cpuid[17]=00000000 00000000 00000000 00000000
basic_cpuid[18]=00000000 00000000 00000000 00000000
basic_cpuid[19]=00000000 00000000 00000000 00000000
basic_cpuid[20]=00000001 0000000f 00000007 00000000
basic_cpuid[21]=00000002 000000e2 00000000 00000000
basic_cpuid[22]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[23]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[24]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[25]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[26]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[27]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[28]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[29]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[30]=00000a8c 00000ce4 00000064 00000000
basic_cpuid[31]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[0]=80000008 00000000 00000000 00000000
ext_cpuid[1]=00000000 00000000 00000121 2c100800
ext_cpuid[2]=65746e49 2952286c 726f4320 4d542865
ext_cpuid[3]=35692029 3034362d 50432030 20402055
ext_cpuid[4]=30372e32 007a4847 00000000 00000000
ext_cpuid[5]=00000000 00000000 00000000 00000000
ext_cpuid[6]=00000000 00000000 01006040 00000000
ext_cpuid[7]=00000000 00000000 00000000 00000100
ext_cpuid[8]=00003027 00000000 00000000 00000000
ext_cpuid[9]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[10]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[11]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[12]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[13]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[14]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[15]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[16]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[17]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[18]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[19]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[20]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[21]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[22]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[23]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[24]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[25]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[26]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[27]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[28]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[29]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[30]=00000a8c 00000ce4 00000064 00000000
ext_cpuid[31]=00000a8c 00000ce4 00000064 00000000
intel_fn4[0]=1c004121 01c0003f 0000003f 00000000
intel_fn4[1]=1c004122 01c0003f 0000003f 00000000
intel_fn4[2]=1c004143 00c0003f 000003ff 00000000
intel_fn4[3]=1c03c163 02c0003f 00001fff 00000006
intel_fn4[4]=00000000 00000000 00000000 00000000
intel_fn4[5]=00000000 00000000 00000000 00000000
intel_fn4[6]=00000000 00000000 00000000 00000000
intel_fn4[7]=00000000 00000000 00000000 00000000
intel_fn11[0]=00000001 00000001 00000100 00000004
intel_fn11[1]=00000004 00000004 00000201 00000004
intel_fn11[2]=00000000 00000000 00000002 00000004
intel_fn11[3]=00000000 00000000 00000003 00000004
intel_fn12h[0]=00000000 00000000 00000000 00000000
intel_fn12h[1]=00000000 00000000 00000000 00000000
intel_fn12h[2]=00000000 00000000 00000000 00000000
intel_fn12h[3]=00000000 00000000 00000000 00000000
intel_fn14h[0]=00000001 0000000f 00000007 00000000
intel_fn14h[1]=02490002 003f3fff 00000000 00000000
intel_fn14h[2]=00000000 00000000 00000000 00000000
intel_fn14h[3]=00000000 00000000 00000000 00000000
```

**Comment by anrieff** [comment] 2016-10-24 17:57
Thank you very much! I can confirm that the issue reproduces here and my fix is indeed correct. I'll push the commit later this evening.

**Comment by anrieff** [comment] 2016-10-25 02:18
Fixed in e36a08d.

**Closed by anrieff** 2016-10-25 02:18 UTC

**Comment by X0rg** [comment] 2016-10-25 17:12
@anrieff:  Sorry not to have been able to get back to you sooner.
It's a good idea, that's done.

I plan to add a way to use a given raw.txt file inside CPU-X, later. It should help me in testing purposes.

**Comment by wdlkmpx** [comment] 2016-10-25 18:46
I think i have a tar file somewhere that has html files with accurate
info for many processors.

These reports will never stop. I think the current functions are ok
for old processors, but newer ones are confusing and have differente
codenames and stuff even when they look the same.

But this newer processors have model code and so on, it's to identify
them by by that string as well. There are variants, once you see a
huge catalog with details you will understand that there are always
exceptions, and there is not enough people to report all of this, and
probably only a few know where to report. Maybe most people get their
processor info wrong...

**Comment by anrieff** [comment] 2016-10-27 12:59
BTW, one thing that I have found useful is collecting raw CPUID data from a lot of processors, as it's done in [ucbench](http://anrieff.net/ucbench/). Every result sent to the results DB there has the raw CPUID data, so I can update libcpuid based on the discrepancies. I'm thinking of (but haven't done yet) creating a script that automates the catching discrepancies, binning them by cpu model number, etc.
